id: P005427
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG1616
  title: ཀུན་མཁྱེན་ཆོས་འབྱུང་གནས་ཀྱི་གསུང་རྒྱུན་དྲི་མ་མེད་པ་བུང་བའི་དགའ་སྟོན་དགེ་འདུན་ཉི་ཤུའི་རྣམ་གཞག
  author: ''
  volumes:
    8914fa702dbb475c83b44acda7e43d99:
      image_group_id: I1KG1708
      title: ''
      volume_number: 1
      total_pages: 93
      base_file: v001.txt
